---
title: "Situation épidémiologique de la diarrhée aiguë après l'ouragan Matthew"
subtitle: "Département de la Grand’ Anse, Haiti"
# author: "Jonathan Polonsky - WHO/WHE/HIM"
author: "MSPP/PAHO"
date: '\today'
fontsize: 11pt
output:
  # mintr::mint_beamer:
  beamer_presentation:
    theme: m
    slide_level: 2
    pandoc_args: ['--latex-engine=xelatex']
    includes:
      in_header: header.tex
      after_body: footer.tex
params:
  dep_san: DSGA
---

```{r, cache=FALSE, message=FALSE, echo=FALSE, warning=FALSE, results='hide'}
knitr::opts_chunk$set(cache=FALSE, message=FALSE, echo=FALSE, warning=FALSE, results='asis')
knitr::knit_hooks$set(inline = function(x) if (is.numeric(x)) round(x, 1) )

list_depts <- params$dep_san

source('functions.R')

# list data sheets to be read in (all communes per dept)
list_db_paths <- dir('data', full.names = TRUE)
# list_depts <-
  # list_db_paths[str_detect(list_db_paths, 'Surveillance Cholera_2015_2016')] %>% 
  # str_replace_all(c('data/' = '', '[-_]Surveillance Cholera.*' = ''))

list_dat_raw <- map(list_depts, WrangleData) %>% set_names(list_depts)
list_dat <- map(list_dat_raw, MergeAges)

# plot by day
list_hist_day <- map(list_dat, PlotHistDay)

# by week & commune
list_hist_week_commune <- map(list_dat, PlotHistWeekCommune)

# by day & inst
list_hist_day_inst <- map(list_dat, PlotHistDayInst)

# tables
list_table <- map(list_dat, MakeTable)

# map
list_df_map <- map(list_dat, WrangleDataMapPopAR)
list_map <- map(list_df_map, MakeMapAR)
```

## Tendance des cas de diarrhées aigues

```{r}
list_hist_day[[list_depts]]
```

## Taux d'attaque par 10,000 personnes, par commune

```{r}
list_map[[list_depts]]
```

## Tendance des cas de diarrhées aigues, par commune

```{r}
list_hist_week_commune[[list_depts]]
```

## Tendance des cas de diarrhées aigues, par CTC

```{r}
list_hist_day_inst[[list_depts]]
```
