---
output:
  tufte::tufte_handout:
    latex_engine: pdflatex
    pandoc_args: [
      '--include-in-header', 'styles.sty', 
      '--include-before-body', 'titlepage.tex'
    ]
params:
  dep_san: DSS
---

```{r, cache=FALSE, message=FALSE, echo=FALSE, warning=FALSE, results='hide'}
knitr::opts_chunk$set(cache=FALSE, message=FALSE, echo=FALSE, warning=FALSE, results='asis')
knitr::knit_hooks$set(inline = function(x) if (is.numeric(x)) round(x, 1) )

# load('ws.RData')
source('functions.R')

list_db_paths <- dir('data', full.names = TRUE)
# list_depts <-
#   list_db_paths[str_detect(list_db_paths, 'Surveillance Cholera_2015_2016')] %>%
#   str_replace_all(c('data/' = '', '[-_]Surveillance Cholera.*' = ''))
list_depts <- params$dep_san

list_dat_raw <- map(list_depts, WrangleData) %>% set_names(list_depts)
list_dat <- map(list_dat_raw, MergeAges)
list_df_map <- map(list_dat, WrangleDataMapPopAR)
```

<!-- -	Analyse base de données de diarrhées aigues sévères de la Grand’Anse -->
<!-- -	Investigation de décès institutionnels a Dame Marie, Recherche active communautaire et reponse -->
<!-- -	Evaluation de la qualité des données cholera a Dame Marie, Chambellan et Moron -->

# Analyse des données de diarrhées aigues:

```{r, fig.fullwidth = TRUE, fig.cap = paste0("Tendance des cas de diarrhées aigues, ", list_dat[[list_depts]]$date %>% min %>% format('%d %b %Y'), " - ", list_dat[[list_depts]]$date %>% max %>% format('%d %b %Y'), " Grand’Anse (données partielles).")}
# plot by day
list_hist_day <- map(list_dat, PlotHistDay)
list_hist_day[[list_depts]]
```

```{r, fig.fullwidth = F, fig.height = 3, fig.cap = paste0("Répartition des cas de diarrhées aigues par commune, ", list_dat[[list_depts]]$date %>% min %>% format('%d %b %Y'), " - ", list_dat[[list_depts]]$date %>% max %>% format('%d %b %Y'), " Grand’Anse (données partielles).")}
df_pie_cas_vus <- map(list_dat_raw, WrangleDataPie, variable = 'cas_vus')
list_pie_commune <- map(df_pie_cas_vus, PlotPie, colour_scheme = 'RdBu', key = 'commune')
list_pie_commune[[list_depts]]
```

\clearpage

\begin{fullwidth}
\makeatletter\setlength\hsize{\@tufte@fullwidth}\setlength\linewidth{\@tufte@fullwidth}\let\caption\@tufte@orig@caption\makeatother
\footnotesize
```{r, tab_overview}
list_table <- map(list_dat, MakeTable)

if(nrow(list_table[[list_depts]])>1) {rws <- seq(1, nrow(list_table[[list_depts]]) - 1, by = 2)}

list_table[[list_depts]] %>% 
  xtable::xtable(
    caption = paste0("Répartition des cas de diarrhées aigues par CTC/UTC, ", list_dat[[list_depts]]$date %>% min %>% format('%d %b %Y'), " - ", list_dat[[list_depts]]$date %>% max %>% format('%d %b %Y'), " Grand’Anse (données partielles)."), 
    digits = 0, label = "tab_overview", align = 'lllrrrr'
  ) %>% 
  print(booktabs = TRUE, caption.placement = "top", add.to.row = list(pos = as.list(rws), command = rep("\\rowcolor{whoblue!15}", length(rws))), include.rownames = FALSE, comment = FALSE, tabular.environment = 'longtable', floating = FALSE)
```
\end{fullwidth}

\newpage

```{r, fig.fullwidth = TRUE, fig.height=5, fig.cap = paste0("Répresentation du taux d'attaque des cas de diarrhées aigues par 10,000 personnes, ", list_dat[[list_depts]]$date %>% min %>% format('%d %b %Y'), " - ", list_dat[[list_depts]]$date %>% max %>% format('%d %b %Y'), " par commune, Grand’Anse (données partielles).")}
list_map <- map(list_df_map, MakeMapAR)
list_map[[list_depts]]
```

\newpage

```{r, fig.fullwidth = TRUE, fig.height=4, fig.cap = paste0("Tendance des cas de diarrhées aigues, ", list_dat[[list_depts]]$date %>% min %>% format('%d %b %Y'), " - ", list_dat[[list_depts]]$date %>% max %>% format('%d %b %Y'), " par commune, Grand’Anse (données partielles).")}
# by week & commune
list_hist_week_commune <- map(list_dat, PlotHistWeekCommune)
list_hist_week_commune[[list_depts]]
```

\newpage

```{r, fig.fullwidth = FALSE, fig.cap = paste0("Répartition des cas de diarrhées aigues par tranche d'age, ", list_dat[[list_depts]]$date %>% min %>% format('%d %b %Y'), " - ", list_dat[[list_depts]]$date %>% max %>% format('%d %b %Y'), " par commune, Grand’Anse (données partielles).")}
list_pie_age <- map(df_pie_cas_vus, PlotPie, colour_scheme = 'RdBu', facet_var = 'commune')
list_pie_age[[list_depts]]
```

\newpage

```{r, fig.fullwidth = TRUE, fig.height=4, fig.cap = paste0("Tendance des cas de diarrhées aigues, ", list_dat[[list_depts]]$date %>% min %>% format('%d %b %Y'), " - ", list_dat[[list_depts]]$date %>% max %>% format('%d %b %Y'), " par CTC, Grand’Anse (données partielles).")}
# by day & inst
list_hist_day_inst <- map(list_dat, PlotHistDayInst)
list_hist_day_inst[[list_depts]]
```

